version: "2"
services:
  kibana:
    image: kibana:5.5
    container_name: userline-kibana
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5.5
    container_name: userline-elasticsearch
    restart: always
    command: "elasticsearch -Enode.name=userline"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  neo4j:
    image: neo4j:3.2
    container_name: userline-neo4j
    restart: always
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neodata:/data

volumes:
  neodata:
  esdata:
